// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";

/**
 * @title IVerifier
 * @notice Interface for Groth16 verifier contract generated by snarkjs
 */
interface IVerifier {
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[] memory input
    ) external view returns (bool);
}

/**
 * @title RollupGateway
 * @notice L1 contract that accepts ZK rollup batches and verifies proofs
 *
 * This contract serves as the bridge between L2 voting and L1 security.
 * It verifies ZK proofs and stores state root commitments from L2.
 */
contract RollupGateway is Ownable, Pausable {
    
    /// @notice Current batch counter
    uint256 public batchCount;
    
    /// @notice Verifier contract address
    IVerifier public verifier;
    
    /// @notice Mapping from batch ID to state root
    mapping(uint256 => bytes32) public stateRoots;
    
    /// @notice Mapping from batch ID to timestamp
    mapping(uint256 => uint256) public batchTimestamps;
    
    /// @notice Mapping from election ID to initial state root
    mapping(bytes32 => bytes32) public electionStateRoots;
    
    /// @notice Mapping from nullifier to used status (prevents double voting)
    mapping(bytes32 => bool) public usedNullifiers;
    
    /// @notice Mapping from batch ID to vote count
    mapping(uint256 => uint256) public batchVoteCounts;
    
    /// @notice Emergency exit guardian (multi-sig in production)
    address public guardian;
    
    /// @notice Maximum batch size allowed
    uint256 public maxBatchSize;
    
    /// @notice Verification key hash (for ensuring correct circuit)
    bytes32 public verificationKeyHash;
    
    // Events
    event BatchSubmitted(
        uint256 indexed batchId,
        bytes32 indexed electionId,
        bytes32 oldStateRoot,
        bytes32 newStateRoot,
        uint256 voteCount,
        uint256 timestamp
    );
    
    event BatchVerified(uint256 indexed batchId, bool success);
    
    event EmergencyExitInitiated(bytes32 indexed electionId, uint256 timestamp);
    
    event GuardianChanged(address indexed oldGuardian, address indexed newGuardian);
    
    // Custom errors
    error InvalidBatchSize();
    error InvalidProof();
    error InvalidStateTransition();
    error NullifierAlreadyUsed(bytes32 nullifier);
    error InvalidVerificationKey();
    error GuardianOnly();
    error InvalidElection();
    
    /**
     * @notice Constructor
     * @param _verifier Address of the Groth16 verifier contract
     * @param _verificationKeyHash Hash of the verification key
     * @param _maxBatchSize Maximum votes per batch
     */
    constructor(
        address _verifier,
        bytes32 _verificationKeyHash,
        uint256 _maxBatchSize
    ) Ownable(msg.sender) {
        require(address(_verifier) != address(0), "Invalid verifier address");
        require(_maxBatchSize > 0 && _maxBatchSize <= 1000, "Invalid batch size");

        verifier = IVerifier(_verifier);
        verificationKeyHash = _verificationKeyHash;
        maxBatchSize = _maxBatchSize;
        batchCount = 0;
        guardian = msg.sender;
    }
    
    /**
     * @notice Submit a batch of votes with ZK proof
     * @param _electionId Unique election identifier
     * @param _batchId Batch number (should equal current batchCount)
     * @param _oldStateRoot Previous state root
     * @param _newStateRoot New state root after applying votes
     * @param _voteCommitments Array of vote commitments
     * @param _nullifiers Array of nullifiers for double-vote prevention
     * @param _candidateIds Array of voted candidate IDs
     * @param _proof Groth16 proof (a, b, c points)
     * @param _input Public inputs to the circuit
     */
    function submitBatch(
        bytes32 _electionId,
        uint256 _batchId,
        bytes32 _oldStateRoot,
        bytes32 _newStateRoot,
        bytes32[] calldata _voteCommitments,
        bytes32[] calldata _nullifiers,
        uint256[] calldata _candidateIds,
        uint256[8] calldata _proof,
        uint256[] calldata _input
    ) external onlyOwner whenNotPaused {
        // Validate inputs
        require(_batchId == batchCount, "Invalid batch ID");
        require(_voteCommitments.length == _nullifiers.length, "Array length mismatch");
        require(_voteCommitments.length == _candidateIds.length, "Array length mismatch");
        require(_voteCommitments.length <= maxBatchSize, "Batch size exceeds maximum");
        require(_voteCommitments.length > 0, "Empty batch not allowed");
        
        // Verify election exists
        bytes32 currentRoot = electionStateRoots[_electionId];
        if (currentRoot == bytes32(0)) {
            // First batch for this election
            require(_oldStateRoot == bytes32(0), "First batch must start from zero root");
            currentRoot = _oldStateRoot;
        } else {
            require(_oldStateRoot == currentRoot || _oldStateRoot == stateRoots[_batchId - 1], 
                "Invalid old state root");
        }
        
        // Verify nullifiers haven't been used
        for (uint256 i = 0; i < _nullifiers.length; i++) {
            if (usedNullifiers[_nullifiers[i]]) {
                revert NullifierAlreadyUsed(_nullifiers[i]);
            }
            usedNullifiers[_nullifiers[i]] = true;
        }
        
        // Verify ZK proof
        bool isValid = _verifyProof(_proof, _input);
        if (!isValid) {
            emit BatchVerified(_batchId, false);
            revert InvalidProof();
        }
        
        // Update state
        stateRoots[_batchId] = _newStateRoot;
        batchTimestamps[_batchId] = block.timestamp;
        electionStateRoots[_electionId] = _newStateRoot;
        batchVoteCounts[_batchId] = _voteCommitments.length;
        
        batchCount++;
        
        emit BatchSubmitted(
            _batchId,
            _electionId,
            _oldStateRoot,
            _newStateRoot,
            _voteCommitments.length,
            block.timestamp
        );
        emit BatchVerified(_batchId, true);
    }
    
    /**
     * @notice Initialize an election on L1
     * @param _electionId Unique election identifier
     * @param _initialStateRoot Initial Merkle root of registered voters
     */
    function initializeElection(bytes32 _electionId, bytes32 _initialStateRoot) 
        external onlyOwner 
    {
        require(electionStateRoots[_electionId] == bytes32(0), "Election already initialized");
        electionStateRoots[_electionId] = _initialStateRoot;
    }
    
    /**
     * @notice Emergency withdrawal for a voter
     * Allows voters to exit with their vote data if sequencer fails
     */
    function emergencyExit(
        bytes32 _electionId,
        uint256 _voterIndex,
        bytes32 _voterSecret,
        bytes32 _voteCommitment
    ) external whenPaused {
        require(msg.sender == guardian, "Only guardian can call this");
        
        emit EmergencyExitInitiated(_electionId, block.timestamp);
        // In production, implement full emergency exit logic
    }
    
    /**
     * @notice Verify Groth16 proof
     */
    function _verifyProof(
        uint256[8] calldata _proof,
        uint256[] calldata _input
    ) internal view returns (bool) {
        // Parse proof components
        uint256[2] memory a = [_proof[0], _proof[1]];
        uint256[2][2] memory b = [
            [_proof[2], _proof[3]],
            [_proof[4], _proof[5]]
        ];
        uint256[2] memory c = [_proof[6], _proof[7]];
        
        return verifier.verifyProof(a, b, c, _input);
    }
    
    /**
     * @notice Update guardian address
     */
    function setGuardian(address _newGuardian) external onlyOwner {
        require(_newGuardian != address(0), "Invalid guardian address");
        emit GuardianChanged(guardian, _newGuardian);
        guardian = _newGuardian;
    }
    
    /**
     * @notice Pause the contract (emergency stop)
     */
    function pause() external {
        require(msg.sender == owner() || msg.sender == guardian, "Not authorized");
        _pause();
    }
    
    /**
     * @notice Unpause the contract
     */
    function unpause() external onlyOwner {
        _unpause();
    }
    
    /**
     * @notice Update maximum batch size
     */
    function setMaxBatchSize(uint256 _newSize) external onlyOwner {
        require(_newSize > 0 && _newSize <= 1000, "Invalid batch size");
        maxBatchSize = _newSize;
    }
    
    /**
     * @notice Get current election state root
     */
    function getCurrentStateRoot(bytes32 _electionId) external view returns (bytes32) {
        return electionStateRoots[_electionId];
    }
    
    /**
     * @notice Get batch details
     */
    function getBatchDetails(uint256 _batchId) external view returns (
        bytes32 stateRoot,
        uint256 timestamp,
        uint256 voteCount
    ) {
        return (stateRoots[_batchId], batchTimestamps[_batchId], batchVoteCounts[_batchId]);
    }
}
