const { buildPoseidon } = require("circomlibjs");
const fs = require("fs");
const path = require("path");
const snarkjs = require("snarkjs");

/**
 * generateBatchStateInput.js — Layer 2: Generate batch state transition input
 *
 * This runs on the OPERATOR after receiving and verifying individual vote proofs.
 * It builds the state tree transitions and generates the batch proof input.
 *
 * The operator DOES NOT need voter secrets — only (candidate, vote) from verified proofs.
 */

async function generateBatchStateInput() {
    const poseidon = await buildPoseidon();
    const F = poseidon.F;

    // Load individual vote proofs (generated by voters)
    const voteProofsPath = path.join(__dirname, "..", "build", "vote_proofs.json");
    if (!fs.existsSync(voteProofsPath)) {
        console.error("Error: vote_proofs.json not found. Run generateVoteProof.js first.");
        process.exit(1);
    }
    const voteProofs = JSON.parse(fs.readFileSync(voteProofsPath, "utf8"));

    // Load voter merkle root
    const proofsData = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "merkleProofs.json"), "utf8"));
    const voterMerkleRoot = BigInt(proofsData.merkleRoot);

    const batchSize = 16;
    const stateLevels = 5;
    const numStateLeaves = 2 ** stateLevels;

    console.log("=== Generating Batch State Input (Layer 2) ===");
    console.log("Batch size:", batchSize);
    console.log(`Processing ${voteProofs.length} verified vote proofs\n`);

    // Step 1: Verify each individual proof off-chain
    const vkeyPath = path.join(__dirname, "..", "build", "vote_proof_verification_key.json");
    if (fs.existsSync(vkeyPath)) {
        console.log("--- Verifying individual vote proofs off-chain ---");
        const vkey = JSON.parse(fs.readFileSync(vkeyPath, "utf8"));
        for (let i = 0; i < voteProofs.length; i++) {
            const isValid = await snarkjs.groth16.verify(
                vkey,
                voteProofs[i].publicSignals,
                voteProofs[i].proof
            );
            if (!isValid) {
                console.error(`  ✗ Vote proof ${i + 1} is INVALID — rejecting`);
                process.exit(1);
            }
            console.log(`  ✓ Vote proof ${i + 1} verified (candidate=${voteProofs[i].candidate})`);
        }
        console.log("");
    } else {
        console.log("Warning: vote_proof_verification_key.json not found, skipping off-chain verification\n");
    }

    // Step 2: Build state transitions from verified vote data
    const stateLeaves = new Array(numStateLeaves).fill(0n);

    function buildStateTree(leaves) {
        const tree = [];
        const level0 = leaves.map(v => F.toObject(poseidon([v])));
        tree.push(level0);

        for (let level = 0; level < stateLevels; level++) {
            const current = tree[level];
            const next = [];
            for (let i = 0; i < current.length; i += 2) {
                const left = current[i];
                const right = i + 1 < current.length ? current[i + 1] : 0n;
                next.push(F.toObject(poseidon([left, right])));
            }
            tree.push(next);
        }
        return tree;
    }

    function getStateProof(tree, index) {
        const pathElements = [];
        let currentIndex = index;

        for (let level = 0; level < stateLevels; level++) {
            const currentLevel = tree[level];
            const isLeft = currentIndex % 2 === 0;
            const siblingIndex = isLeft ? currentIndex + 1 : currentIndex - 1;
            const sibling = siblingIndex < currentLevel.length ? currentLevel[siblingIndex] : 0n;
            pathElements.push(sibling.toString());
            currentIndex = Math.floor(currentIndex / 2);
        }

        return pathElements;
    }

    const candidates = [];
    const votes = [];
    const nullifierHashes = [];
    const isNoOps = [];
    const stateLeafIndices = [];
    const stateOldValues = [];
    const stateNewValues = [];
    const statePathElements = [];

    let stateTree = buildStateTree(stateLeaves);
    const preStateRoot = stateTree[stateLevels][0];

    for (let i = 0; i < batchSize; i++) {
        if (i < voteProofs.length) {
            // Real vote from a verified individual proof
            const vp = voteProofs[i];
            const candidateIdx = vp.candidate;
            const voteVal = vp.vote;

            candidates.push(candidateIdx.toString());
            votes.push(voteVal.toString());
            nullifierHashes.push(vp.nullifierHash.toString());
            isNoOps.push("0");

            const oldVal = stateLeaves[candidateIdx];
            const proof = getStateProof(stateTree, candidateIdx);

            stateLeafIndices.push(candidateIdx.toString());
            stateOldValues.push(oldVal.toString());

            const newVal = oldVal + BigInt(voteVal);
            stateNewValues.push(newVal.toString());
            statePathElements.push(proof);

            stateLeaves[candidateIdx] = newVal;
            stateTree = buildStateTree(stateLeaves);

            console.log(`Vote ${i + 1}: Candidate ${candidateIdx} (vote=${voteVal}), tally: ${oldVal} → ${newVal}`);
        } else {
            // Padding (noOp)
            candidates.push("0");
            votes.push("0");
            nullifierHashes.push("0");
            isNoOps.push("1");

            const proof = getStateProof(stateTree, 0);
            stateLeafIndices.push("0");
            stateOldValues.push(stateLeaves[0].toString());
            stateNewValues.push(stateLeaves[0].toString());
            statePathElements.push(proof);

            console.log(`Vote ${i + 1}: NoOp (padding)`);
        }
    }

    const postStateRoot = stateTree[stateLevels][0];

    // Batch nullifier hash commitment
    const batchNullifierHash = F.toObject(
        poseidon(nullifierHashes.map(n => BigInt(n)))
    );

    const batchInput = {
        preStateRoot: preStateRoot.toString(),
        postStateRoot: postStateRoot.toString(),
        batchNullifierHash: batchNullifierHash.toString(),
        voterMerkleRoot: voterMerkleRoot.toString(),
        candidates,
        votes,
        nullifierHashes,
        isNoOp: isNoOps,
        stateLeafIndices,
        stateOldValues,
        stateNewValues,
        statePathElements
    };

    const outputPath = path.join(__dirname, "..", "build", "batch_state_input.json");
    fs.writeFileSync(outputPath, JSON.stringify(batchInput, null, 2));

    console.log("\n=== Batch State Input Generated ===");
    console.log("Pre-state root:", preStateRoot.toString().substring(0, 30) + "...");
    console.log("Post-state root:", postStateRoot.toString().substring(0, 30) + "...");
    console.log("Batch nullifier hash:", batchNullifierHash.toString().substring(0, 30) + "...");
    console.log("Saved to:", outputPath);

    // Show final tally
    console.log("\n=== Vote Tally ===");
    for (let c = 0; c < 5; c++) {
        console.log(`  Candidate ${c}: ${stateLeaves[c]} votes`);
    }

    return batchInput;
}

if (require.main === module) {
    generateBatchStateInput()
        .then(() => {
            console.log("\nDone!");
            process.exit(0);
        })
        .catch(err => {
            console.error("Error:", err);
            process.exit(1);
        });
}

module.exports = { generateBatchStateInput };
